version: '3'

services:
  back:
    build: ./php
    volumes:
      - ./php/src:/src
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 8000:80
    volumes:
      - ./php/src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src
  db:
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: